insert into author (username, name, bio) values ('frankh', 'Frank Herbert', 'Franklin Patrick Herbert, Jr. (October 8, 1920 - February 11, 1986) was an American science fiction writer best known for the novel Dune and its five sequels.')
insert into book (title) values ('Dune')
insert into book (title) values ('Dune Messiah')
insert into book (title) values ('Children of Dune')
insert into book_authors (authors_id, books_id) values (1, 1)
insert into book_authors (authors_id, books_id) values (1, 2)
insert into book_authors (authors_id, books_id) values (1, 3)

insert into author (username, name, bio) values ('philipkd', 'Philip K. Dick', 'Philip Kindred Dick (December 16, 1928 - March 2, 1982) was an American writer known for his work in science fiction.')
insert into book (title) values ('Do Androids Dream of Electric Sheep?')
insert into book (title) values ('The Man in the High Castle')
insert into book (title) values ('A Scanner Darkly')
insert into book_authors (authors_id, books_id) values (2, 4)
insert into book_authors (authors_id, books_id) values (2, 5)
insert into book_authors (authors_id, books_id) values (2, 6)

-- A jointly written book!
insert into book(title) values ('The Amalgamation')
insert into book_authors (authors_id, books_id) values (1, 7)
insert into book_authors (authors_id, books_id) values (2, 7)
